title: Daniel Tunde Abbey
logo: Headshot.PNG
description: "Hi there! 👋 I'm Daniel Tunde Abbey, a passionate Data Analyst with expertise in data visualization, statistical analysis, and business intelligence tools like Python, SQL, Power BI, Tableau, and Excel. My work revolves around transforming complex datasets into actionable insights that drive decision-making and solve real-world problems.Take a look at my repositories to explore projects on sales analysis, customer feedback, HR metrics, and more.🚀"

#show_downloads: true
theme: jekyll-theme-minimal
